name: cyclfit
description: "A complete cycling fitness app with workout tracking, health monitoring, and gamification features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1

  # Map and Location
  flutter_map: ^8.2.1
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  sensors_plus: ^6.1.2

  # Database and Storage
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_secure_storage: ^9.0.0

  # Backend and API
  supabase_flutter: ^2.0.0
  dio: ^5.3.0
  dio_cache_interceptor: ^4.0.3
  http: ^1.1.0

  # State Management and Navigation
  provider: ^6.1.0
  go_router: ^16.2.1

  # Charts and Data Visualization
  fl_chart: ^1.1.0

  # Health Integration
  health: ^13.1.4
  permission_handler: ^12.0.1

  # Utility Packages
  share_plus: ^11.1.0
  image_picker: ^1.0.0
  connectivity_plus: ^6.1.5
  intl: ^0.20.2
  uuid: ^4.1.0
  cached_network_image: ^3.3.0
  flutter_markdown: ^0.7.7+1

  # Authentication
  google_sign_in: ^7.1.1

  # Background Processing
  workmanager: ^0.9.0+3

  # Animations and UI Enhancements
  lottie: ^3.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
